### ISSUE TITLE
Seconds incorrectly displayed during setup

### ISSUE THREAD

**Issue by mrabsinthe** [stifler97/modifytokenlifetime#3]
**Describe the bug**
It is more a cosmetic issue instead of a bug... During setup, seconds are incorrectly displayed, for example 22hours being displayed as 7920000 instead of 79200. It is corrected as soon as you hit save button.

![seconds](https://user-images.githubusercontent.com/31688689/181171853-a45d4917-ac64-4a17-8d55-b2d2b6de5eab.png)

**Comment by stifler97** [comment]
Thanks for the report.

**Comment by stifler97** [comment]
Actually the calculation of those seconds are different from how it is saved in database. I might have done some extra calculation by mistake. I will add a fix and update just after I find the bug.

**Comment by stifler97** [comment]
bug is valid and I will update it soon with a fix

**Comment by stifler97** [comment]
#4 is a mistake. Just ignore it. The fix is in #5 
Thanks @mrabsinthe for the report
